version: '3.1'

services:

  db:
    image: postgres:11.17-alpine
    environment:
      POSTGRES_DB: 'foton_db'
      POSTGRES_USER: 'foton_user'
      POSTGRES_PASSWORD: 'qwerty123'
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '5432:5432'

    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - '8080:8080'

    depends_on:
      - db

