version: '3.1'

services:

  db:
    image: postgres:11.17-alpine
    environment:
      POSTGRES_DB: 'foton_db'
      POSTGRES_USER: 'foton_user'
      POSTGRES_PASSWORD: 'qwerty123'
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    ports:
      - '8080:8080'

    depends_on:
      - db

