version: "3.9"

services:

#  nginx_server:
#    container_name: "nginx_server"
#    restart: always
#    image: nginx:alpine
#    depends_on:
#      - foton_handler_backend
#
#    ports:
#      - "2082:80"
#
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#
#
#  foton_handler_backend:
#    container_name: "foton_handler_backend"
#    image: foton_handler_backend
#    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile
#
#    command: bash -c 'while ! nc -z postgresql_db 5432; do sleep 1; done; alembic upgrade head; uvicorn main:app --host 0.0.0.0'
#
#    environment:
#      TZ: Europe/Moscow
#      DB_HOST: postgresql_db
#
#    depends_on:
#      - postgresql_db

  postgresql_db:
    container_name: "postgresql_db"
    image: postgres:11.17-alpine
    restart: always
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_DB: "foton_db"
      POSTGRES_USER: "foton_user"
      POSTGRES_PASSWORD: "qwerty123"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    volumes:
      - ../init postgres docker:/docker-entrypoint-initdb.d
      - ../pg data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  adminer:
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - "8080:8080"

    depends_on:
      - postgresql_db