"""init v 0.02

Revision ID: 6b9e6c116073
Revises: 6389937af08e
Create Date: 2022-11-15 17:17:25.015172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9e6c116073'
down_revision = '6389937af08e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('controller_data_controller_id_fkey', 'controller_data', type_='foreignkey')
    op.create_foreign_key(None, 'controller_data', 'controllers', ['controller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'controller_data', type_='foreignkey')
    op.create_foreign_key('controller_data_controller_id_fkey', 'controller_data', 'controllers', ['controller_id'], ['id'])
    # ### end Alembic commands ###
