"""v 0.03

Revision ID: 75a293e36163
Revises: 6b9e6c116073
Create Date: 2022-11-23 17:25:57.956440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a293e36163'
down_revision = '6b9e6c116073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controllers', sa.Column('local_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controllers', 'local_address')
    # ### end Alembic commands ###
