"""v 0.01

Revision ID: dfaa688b18d2
Revises: 
Create Date: 2022-10-31 15:27:08.058275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfaa688b18d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_super_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('controllers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('controller_address', sa.String(length=20), nullable=True),
    sa.Column('login', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controller_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vout', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('charge', sa.Integer(), nullable=True),
    sa.Column('relay', sa.Integer(), nullable=True),
    sa.Column('vch', sa.Integer(), nullable=True),
    sa.Column('data_datetime', sa.DateTime(), nullable=True),
    sa.Column('controller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controller_data')
    op.drop_table('controllers')
    op.drop_table('users')
    # ### end Alembic commands ###
